on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  CI: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install
        run: npm install --no-package-lock
      - name: Test
        run: npm test
